PUT  http://localhost:3003/api/blogs/6411fbd5e950e9797a2c9050
Content-Type: application/json

{
    "title": "TESTING COMMENT",
    "author": "TESTING COMMENT",
    "url": "TESTING COMMENT",
    "likes": 5,
    "comments": {"userID":2, "comment":"WORK"}
}